config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # 自作のユーザーモデルにするとき注意
    path('', include('study.urls')),
    path('', include('register.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    # ログイン
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # メール登録
    path('user_create/',
         views.UserCreate.as_view(), name='user_create'),
    path('user_create/done',
         views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/',
         views.UserCreateComplete.as_view(), name='user_create_complete'),
    # ユーザー情報閲覧・更新ページ
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    # パスワード変更ページと再設定ページ
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    # パスワード忘れ
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),


]

study/urls.py
from django.urls import path
from .import views

app_name = 'study'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/', views.CategoryView.as_view(),
         name='category'),  # 教科選択した後の表示リスト
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('comment/<int:post_pk>', views.CommentView.as_view(), name='comment'),
    path('new/', views.PostNewView, name='new'),  # 問題作成
    path('record_creat/', views.RecordCreatView,
         name='record_creat'),  # 作成画面(時間レコード)
    path('record_list/', views.RecordListView.as_view(),
         name='record_list'),  # リスト画面(時間レコード)
    path('r^/record_delete/<int:pk>/', views.RecordDeleteView.as_view(),
         name='record_delete'),  # 削除画面(時間レコード)
    path('graph/', views.GraphView, name='graph'),
    path('test_creat/', views.TestCreatView,
         name='test_creat'),  # 作成画面(テスト結果入力画面)


]

study/models.py
from config.settings import STATIC_ROOT
from django.db import models
from django.utils import timezone
from django.conf import settings

# from django.contrib.auth.models import User


class Category(models.Model):
    # カテゴリ 管理画面でのみ編集できる
    name = models.CharField('カテゴリ名', max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    # 管理サイトでの一覧表示用

    def __str__(self):
        return self.name


class Post(models.Model):
    # 問題の投稿
    title = models.TextField('問題', max_length=255)
    text = models.TextField('答え')

    created_at = models.DateTimeField('作成日', default=timezone.now)
    # on_delete = models.PROTECT カテゴリモデルと紐づいているから削除できない
    category = models.ForeignKey(
        Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    # ブログのコメント
    name = models.CharField('お名前', max_length=30, default='名無し')
    text = models.TextField('コメント')
    post = models.ForeignKey(Post, verbose_name='紐づく記事',
                             on_delete=models.PROTECT)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:10]


class Record(models.Model):
    '''勉強した時間の保存'''
    category = models.CharField(
        verbose_name='教科', blank=True, null=True, max_length=10)
    time = models.CharField(verbose_name="分", blank=True,
                            null=True,  max_length=10)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    # created_at = models.DateField('いつ', blank=True, null=True)
    # on_delete = models.PROTECT カテゴリモデルと紐づいているから削除できない
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        # '教科 - 時間' のように返す
        return '{} - {}'.format(self.category, self.time)


class Test(models.Model):
    '''テスと結果の保存'''
    japanese = models.IntegerField(
        verbose_name='国語', blank=True, null=True)
    math = models.IntegerField(
        verbose_name='数学', blank=True, null=True)
    english = models.IntegerField(
        verbose_name='英語', blank=True, null=True)
    science = models.IntegerField(
        verbose_name='理科', blank=True, null=True)
    social_studies = models.IntegerField(
        verbose_name='社会', blank=True, null=True)
    date = models.DateField('いつまでに', blank=True,
                            null=True)  # このDateFieldが対象です。

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        # '日付 - ユーザー' のように返す
        return '{} - {}'.format(self.date, self.author)

study/views.py
from re import X
from django.db.models import Q
from django.http.response import HttpResponse  # Qオブジェクトは、モデルのデータの中からor検索をする
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from .forms import CommentCreateForm, PostCreateForm, RecordCreateForm, TestForm
from .models import Post, Category, Comment, Record, Test
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib import messages  # ラジオ
from django.views.generic.edit import FormView

# グラフ用///////////////////////////////
import plotly.graph_objects as go
# import plotly.express as px
import pandas as pd
import datetime
import numpy as np
import plotly.io as pio
import plotly.offline as po
import plotly.figure_factory as ff
from django_pandas.io import read_frame
import plotly.express as px  # 折線グラフで追加
from plotly.subplots import make_subplots #グラフの融合


# render 単純なテンプレートとしてHttpResponseをreturnするときのショートカット
# reverse url.pyで決めた名前を解析する関数
# reverse_lazy reverseをクラスベースビューのクラス変数として書くときに利用

class IndexView(generic.ListView):
    # リスト表示用
    model = Post
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at')  # -で降順
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset


# カテゴリ検索


class CategoryView(generic.ListView):
    # カテゴリ別のリスト
    model = Post
    paginate_by = 10

    def get_queryset(self):
        """
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)
        """
        category_pk = self.kwargs['pk']
        queryset = Post.objects.order_by(
            '-created_at').filter(category__pk=category_pk)
        return queryset


class DetailView(generic.DetailView):
    model = Post


class CommentView(generic.CreateView):
    model = Comment
    #fields = ('name', 'text')
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['post_pk']
        comment = form.save(commit=False)  # コメントはDBに保存されていません
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()  # ここでDBに保存
        return redirect('study:detail', pk=post_pk)


# class PostIndexView(generic.ListView):
#     model = Post

@login_required
def PostNewView(request):
    # params = {'message': 'newです'}
    params = {'message': '', 'form': None}
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():  # フォームに入力された値にエラーがないかをバリデートする
            post = form.save(commit=False)
            post.author = request.user  # ログインユーザーをformに入れている
            post.save()
            print('問題を作成しました。')
            # return redirect('new')
        else:
            params['message'] = '再入力してください'
            params['form'] = form
    else:
        params['form'] = PostCreateForm()
    return render(request, 'study/post_input.html', params)
    # return render(request, 'study/post_input.html', params)


# 一覧画面
# class RecordListView(TemplateView):
class RecordListView(generic.ListView):
    # テーブル連携
    model = Record
    # レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "record_list"
    # テンプレートファイル連携
    template_name = "study/record_list.html"

# 削除画面


class RecordDeleteView(generic.DeleteView):
    model = Record
    template_name = "record_delete.html"
    # 削除後のリダイレクト先
    success_url = reverse_lazy("study:record_list")


def RecordCreatView(request):
    # params = {'message': 'newです'}
    params = {'message': '', 'form': None}
    if request.method == 'POST':
        form = RecordCreateForm(request.POST)
        if form.is_valid():  # フォームに入力された値にエラーがないかをバリデートする
            post = form.save(commit=False)
            post.author = request.user  # ログインユーザーをformに入れている
            post.save()
            print('時間を作成しました。')
            # print(post)
            return redirect('study:record_list')
        else:
            params['message'] = '再入力してください'
            params['form'] = form
    else:
        params['form'] = RecordCreateForm()
    return render(request, 'study/record_input.html', params)

# /////////////////////////////////////////////////////////////
# /  テスト結果登録画面  //////////////////////////////////////
# /////////////////////////////////////////////////////////////
def TestCreatView(request):
    context = {
        'test_form': TestForm()  # base.htmlの変数になる
    }
    return render(request, "study/test_input.html", context)

# /////////////////////////////////////////////////////////////
# /  グラフ表示画面      //////////////////////////////////////
# /////////////////////////////////////////////////////////////


@login_required
def GraphView(request):

    # recordデータの加工///
    record_data = Record.objects.all()
    record_df = read_frame(record_data, fieldnames=[
                           'author', 'created_at', 'category', 'time'])
    record_df1 = record_df.replace(
        {'国語': 5, '数学': 4, '英語': 3, '理科': 2, '社会': 1})
    record_df1['date'] = record_df1['created_at'].dt.strftime(
        "%Y-%m-%d")  # 日付の加工//
    record_df1['time_int'] = record_df1['time'].astype(int)  # 時間の加工
    record_df2 = record_df1.drop(['created_at', 'author'], axis=1)  # 列の削除
    # record_df2.dtypes データの型の確認

    # 日付一覧作成
    base = datetime.date.today()  # 今日の日付
    datenum = 60  # 表示したい日数
    dates = base - np.arange(datenum) * datetime.timedelta(days=1)
    dates_df = pd.DataFrame({'date': dates})
    dates_df['category'] = int(1)  # 日付データにいったんカテゴリ列(国語)を作成
    dates_df.loc[datenum] = [base, 2]  # 最後の行にデータ追加 カテゴリを用意
    dates_df.loc[datenum + 1] = [base, 3]
    dates_df.loc[datenum + 2] = [base, 4]
    dates_df.loc[datenum + 3] = [base, 5]
    dates_df['time_int'] = int(0)  # 日付データにいったん時間をを作成
    # dates_df.dtypes データの型の確認

    # 結合表作成
    comb_df = pd.merge(dates_df, record_df2, on=[
                       'date', 'category', 'time_int'], how='outer')  # 結合
    comb_df['date_str'] = comb_df['date'].astype(str)
    comb_df1 = comb_df.drop(['date'], axis=1)  # 列の削除
    comb_df2 = comb_df1.pivot_table(
        index='category', columns='date_str', values='time_int', aggfunc='sum')  # クロス集計表の作成
    # cate_list=[1,2,3,4,5]
    # add_colum = [i for i in cate_list if i not in comb_df2.columns] #集計データにない列を探す
    # comb_df2[[add_colum]]=int(0) # 集計データにない列を追加する

    # comb_df3 = comb_df2.sort_values('date_str', ascending=False).fillna(0)
    comb_df3 = comb_df2.fillna(0)

    subject = ['国語', '数学', '英語', '理科', '社会']

    # z = np.random.poisson(size=(len(subject), len(dates)))
    z = comb_df3
    x = dates[::-1]  # 逆順にする 今日を左にする
    # y = subject[::-1]

    # plot =[]

    fig = go.Figure(data=go.Heatmap(
        # d = go.Heatmap(
        z=z,  # 色が変化するデータ
        x=x,  # X軸
        y=subject[::-1],   # Y軸
        # # x=(1, 7),  # 縦軸ラベルに表示する値、10刻み
        # # opacity=0.5,  # マップの透明度を0.5に
        colorbar=dict(
            thickness=25,
            thicknessmode='pixels',
            len=1.1,  # カラーバーの長さを0.8に（デフォルトは1）
            lenmode='fraction',
            outlinewidth=0,
            # xanchor = 'right',  # 凡例の表示場所の設定
            # yanchor = 'middle',
            # outlinecolor='gray',  # カラーバーの枠線の色
            # outlinewidth=1,  # カラーバーの枠線の太さ
            # bordercolor='gray',  # カラーバーとラベルを含むカラーバー自体の枠線の色
            # borderwidth=1,  # カラーバーとラベルを含むカラーバー自体の枠線の太さ
            title=dict(
                text='分',
                side='top')  # カラーバーのタイトルをつける位置（デフォルトはtop）
        ),
        colorscale=[
            [0, 'rgb(255,255,255)'],  # NaNに該当する値を灰色にして区別する
            [1, 'rgb(255,20,147)']]))
    # ))

    # plot.append(d)

    # layout = go.Layout(
    # autosize = True,   # HTMLで表示したときページに合わせてリサイズするかどうか
    # width=700, #図の幅を指定
    # height=450,
    # margin=dict(l=50, r=50, t=100, b=50, autoexpand=False),
    # height=450,
    # width=700,

    #     # layout = go.Layout(
    fig.update_layout(
        # title='Study day',
        width=1000,
        height=300,
        template='plotly_dark',

    )
    fig.update_traces(
        # xaxis=dict(showgrid=False),
        # yaxis=dict(
        #     showgrid=False,
        #     scaleanchor=x, #Y軸のスケールをX軸と同じに
        #     scaleratio =1,
        #     autorange = 'reversed'),
        ygap=2,  # y軸の隙間
        xgap=2  # x軸の隙間
    )

    plot_fig_heatmap = fig.to_html(fig, include_plotlyjs=False)
    # heatmapとlineグラフとまとめて返すため、コメントアウト
    # return render(request, "study/graph.html", {
    #     "graph_heatmap": plot_fig_heatmap
    # })

# /  ライングラフ  ////////////////////////////////////////////

    # Testデータの加工///
    test_data = Test.objects.all()
    test_df = read_frame(test_data)
    test_df2 = test_df.sort_values('date', ascending=False)
    # test_df2.dtypes データの型の確認

    fig_line = px.line(test_df2, x='date', y=[
        'japanese', 'math', 'english', 'science', 'social_studies'], color_discrete_sequence=['blue', 'purple', 'yellow', 'red', 'green'], title="折線ぐらふ")

    fig_line.update_xaxes(
        # title="", # X軸タイトルを指定
        # range=(base+datetime.timedelta(days=-60),base), # X軸の最大最小値を指定
        rangeslider={"visible":True}, # X軸に range slider を表示（下図参照）
        )

    fig_line.update_yaxes(
        # title="ランキング", # Y軸タイトルを指定
        autorange = 'reversed', # y軸を逆にする ランキング上位が上表示にした
        # scaleanchor="x",
        # scaleratio=1, # Y軸のスケールをX軸と同じに（plt.axis("equal")
        )

    fig_line.update_layout(
        title="ランキング", # グラフタイトルを設定
        showlegend=True, # 凡例を強制的に表示（デフォルトでは複数系列あると表示）
        # xaxis_type="linear",
        # yaxis_type="log", # X軸はリニアスケール、Y軸はログスケールに
        width=1000,
        height=500, # 図の高さを幅を指定
        template='plotly_dark',
        )


    plot_fig_line = fig_line.to_html(include_plotlyjs='cdn',
                                 full_html=False).encode().decode('unicode-escape')

study/templates/study/base.html
{% load django_bootstrap5 %}
{% load static %}


<!doctype html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  {% block extra_head %}{% endblock %}

  <!--  plotly //////////////////////////////////////////////////  -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />




  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/sanitize.css' %}">


  {% bootstrap_css %}
  {% bootstrap_javascript %}


  <title>minsta</title>
</head>

<body style="background-color: rgba(201, 210, 221, 0.25)">
  <!-- ヘッダー -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <div class="container-fluid">
      <a class="navbar-brand ms-5" href="{% url 'register:top' %}">minsta</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'study:index' %}">Home</a>
          </li>
          <!-- スーパーユーザーか判断 -->
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}

          <!-- ログイン済みか判断 -->
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_detail' user.pk %}">ユーザー情報閲覧</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}">LOG OUT</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}">LOG IN</a>
          </li>
          {% endif %}
        </ul>
        <!-- <form class="d-flex" method="GET" action="{% url 'study:index' %}">
          <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-dark" type="submit">Search</button>
        </form> -->
      </div>
    </div>
  </nav>

  <!-- メイン -->
  <div class="container">
    <div class="row">
      <!-- 右側 -->
      <div class="container col-md-3 mt-3">

        <h1 class="display-3" style="text-align:center;">minsta!</h1>
        <p class="lead" style="text-align:center;"> みんなでSTUDY</p>

        <!-- ログイン済みか判断 -->
        {% if user.is_authenticated %}
        <p style="text-align:center;">{{ user.first_name }}がログイン中</p>
        {% else %}
        <p style="text-align:center;">ログインしてください</p>
        {% endif %}
        <!-- インデントを揃えて保存できない なぜ？ -->


        <div class="d-flex justify-content-evenly mb-3">
          <a class="btn btn-light shadow mr-3" href="{% url 'study:new' %}" role="button">問題を書く</a>
          <a class="btn btn-light shadow" href="{% url 'study:record_list' %}" role="button">学習の状況</a>
          <a class="btn btn-light shadow" href="{% url 'study:graph' %}" role="button">グラフ</a>

        </div>



        <form class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="d-flex justify-content-around">
            <button class='btn btn-dark' type="checkbox" name="category" value="国語">国</button>
            <button class='btn btn-dark' type="checkbox" name="category" value="数学">数</button>
            <button class='btn btn-dark' type="checkbox" name="category" value="英語">英</button>
            <button class='btn btn-dark' type="checkbox" name="category" value="理科">理</button>
            <button class='btn btn-dark' type="checkbox" name="category" value="社会">社</button>
          </div>

          <!-- タイマー -->
          <p id="timerLabel" style="color: white; font-size: 50px; text-align: center">00:00</p>
          <div class="d-flex justify-content-around">
            <input type="button" class="btn btn-dark" name="start" onclick="start()" value="START" id="startBtn">
            <input type="submit" class="btn btn-dark" name="stop" onclick="stop()" value="STOP">
            <input type="button" class="btn btn-dark" onclick="reset()" value="RESET">
          </div>


        </form>
      </div>

      <!-- 中央 -->
      <div class="container col-md-6 mb-3 mt-5">
        <!-- <div class="container col-md-9 mb-3 mt-5"> -->
        {% block content %}
        {% endblock %}
      </div>

      <!-- 左側 -->
      <div class="container col-md-3 mt-5">
        {% block calendar_content %}
        {% endblock %}
      </div>

    </div>
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
    integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
    </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
    integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous">
    </script>






  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>







  <script>
    // タイマーの設定///////////////////////////////////////////////
    var status = 0; // 0:停止中 1:動作中
    var time = 0;
    var startBtn = document.getElementById("startBtn");
    var timerLabel = document.getElementById('timerLabel');

    // STARTボタン
    function start() {
      // 動作中にする
      status = 1;
      // スタートボタンを押せないようにする
      startBtn.disabled = true;

      timer();
    }

    // STOPボタン
    function stop() {
      // 停止中にする
      status = 0;
      // スタートボタンを押せるようにする
      startBtn.disabled = false;
    }

    // RESETボタン
    function reset() {
      // 停止中にする
      status = 0;
      // タイムを0に戻す
      time = 0;
      // タイマーラベルをリセット
      timerLabel.innerHTML = '00:00';
      // スタートボタンを押せるようにする
      startBtn.disabled = false;
    }

    function timer() {
      // ステータスが動作中の場合のみ実行
      if (status == 1) {
        setTimeout(function () {
          time++;

          // 分・秒・ミリ秒を計算
          var min = Math.floor(time / 100 / 60);
          var sec = Math.floor(time / 100);
          var mSec = time % 100;

          if (min < 10) min = "0" + min;
          if (sec >= 60) sec = sec % 60;
          if (sec < 10) sec = "0" + sec;

          // タイマーラベルを更新
          timerLabel.innerHTML = min + ":" + sec;

          // 再びtimer()を呼び出す
          timer();
        }, 10);
      }
    }

    document.onkeydown = function (event) {
      if (event) {
        if (event.keyCode == 32 || event.which == 32) {
          if (status == 1) {
            stop();
          } else if (status == 0) {
            start();
          }
        }
      }
    };
  </script>

</body>

</html>

study/templates/study/comment_form.html
{% extends 'study/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-dark">送信</button>
</form>

{% endblock %}

study/templates/study/graph.html
{% extends 'study/base.html' %}
{% load django_bootstrap5 %}




{% block content %}

<!-- ここにグラフが入る -->
{% autoescape off %}
{{ graph_heatmap }}
{{ graph_line }}

<!-- HTMLコードの文字列が格納されたコンテキスト -->
{% endautoescape %}

{% endblock %}

study/templates/study/post_detail.html
<!-- 詳細ページ コメント付き -->
{% extends 'study/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="card mb-3">
  <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
  <div class="card-body">
    <p>{{ post.created_at }}, {{ post.category }}</p>
    {{ post.text | linebreaksbr | urlize}}
  </div>
</div>

{% for comment in post.comment_set.all %}
<p>
  {{ comment.name }}<br>
  {{ comment.text | linebreaksbr }}
</p>
{% endfor %}

<a class="btn btn-dark" href="{% url 'study:comment' post.pk %}">コメント投稿ページへ</a>
{% endblock %}

study/templates/study/record_delete.html
{% extends 'study/base.html' %}
{% load django_bootstrap5 %}

{% block content %}

<h1>本当に削除しますか?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="削除">
  <!-- <a href="{% url 'study:detail' pk=company.pk %} ">キャンセル</a> -->
</form>

{% endblock %}

study/templates/study/record_list.html
{% extends 'study/base.html' %}
{% load django_bootstrap5 %}




{% block content %}

<a href="{% url 'study:record_creat' %}">勉強時間登録</a>
<a href="{% url 'study:test_creat' %}">テスト結果登録</a>
<!-- もし空じゃなければ中身の処理を実施 -->
{% if record_list %}
<table>
  <tr>
    <td>教科</td>
    <td>時間</td>
    <td>日時</td>
    <td>ユーザー</td>
    <td>削除ボタン</td>
  </tr>
  {% for record in record_list %}
  <tr>
    <td><a href="">{{ record.category }}</a></td>
    <td>{{ record.time }}</td>
    <td>{{ record.created_at }}</td>
    <td>{{ record.author }}</td>
    <td><button type="submit"><a href="delete/{{ record.id }}">>>>削除する</a></button></td>
    <!-- <td><button type="submit"><a href="{% url 'study:record_delete' pk=record.pk %}">>>>削除する</a></button></td> -->
    <!-- <td><a href="/todos/{{ todo.todo_id }}/">{{ record.todo_id }}</a></td> -->
    <!-- <td><a href="/todos/delete/{{ todo.todo_id }}/">削除</a></td> -->
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No todos are available.</p>
{% endif %}

{% endblock %}